#############################################################################
#               _                          _   _      _                _    #
#              | |                        | | (_)    | |              | |   #
#  _ __ ___  __| |_   ___  __   __ _ _ __ | |_ _  ___| |__   ___  __ _| |_  #
# | '__/ _ \/ _` | | | \ \/ /  / _` | '_ \| __| |/ __| '_ \ / _ \/ _` | __| #
# | | |  __/ (_| | |_| |>  <  | (_| | | | | |_| | (__| | | |  __/ (_| | |_  #
# |_|  \___|\__,_|\__,_/_/\_\  \__,_|_| |_|\__|_|\___|_| |_|\___|\__,_|\__| #
#                                                                           #
#############################################################################

# The current version of Redux Anticheat.
# Do not change this version unless you want the config to be reset.
version: 1.0

messages:
    # consolePrefix is the prefix that is used for console logging and information.
    consolePrefix: "&7[&dRedux&7]"
    
    # messagePrefix is the prefix for Rdx in-game, so when someone is flagged.
    messagePrefix: "&d&lRedux &7&l|"
    
    # removalMessage is the message that the player is kicked for or removed for.
    removalMessage:
      - "&8&l&m----------------------------------------------"
      - "&d&lRedux &8> &7You were removed from the server for an unfair advantage"
      - "&8&l&m----------------------------------------------"
      
    removalCommands:
      - "kick %name %removalMessage"
      - "broadcast &8&l&m--------------------------------------------\n&d%name &7was removed from server for an unfair advantage\n&8&l&m--------------------------------------------"
      
# These settings are primarily meant to be for performance.
settings:
    # violationDecay is the amount in long of when some of the total violations are removed from the player, so after a day
    # it could remove 10 vl. By default every five hours it will remove one vl.
    violationDecay: 900

    # globalViolations is the number of total violations a player is kicked for, if they reach 50 in total but only get 2 on one check.
    # it will still remove them from the server
    globalViolations: 50

    # globalSetback is an option to disable movement checks from setting the player down when detected.
    # if false it will disable all setbacks
    globalSetback: true

    # slowServer tells Redux if it should use less intensive checks,
    # this setting is advised for servers 1GB and below.
    slowServer: false
    
    # sendToConsole will tell redux if it should send messages to console such as
    # alerts or changes in checks
    sendToConsole: true

# Learning utilising data logging and checks for irregularities in combat &
# movement, however if slowServer is enabled, Learning will be disabled.
learning:
    # Do you want to enable learning?
    enabled: true
    
    # This enables learning about how a player attacks an entity
    combat: true
    
    # This enables learning about how a player moves.
    movement: true